<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Pages/Site.Master" AutoEventWireup="true" CodeBehind="Game.aspx.cs" Inherits="BUNKER.Pages.Game" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="content-wrapper">
        <div class="player-slider">
            <%--<div class="player-card-wrapper">
                <div class="player-card-inner">
                    <h3 class="player-name" id ="player_name">Valera's hater</h3>
                    <a id ="Job" >
                    <div class="param-name">Професія</div>
                    <div class="param-value">Лікар</div>
                    </a>
                    <a id ="Bio" >
                    <div class="param-name">Біо характеристики</div>
                    <div class="param-value revealed">Жінка, 29 р.</div>
                    </a>
                    <a id ="Heath" >
                    <div class="param-name">Хвороба</div>
                    <div class="param-value">Дислексія</div>
                    </a>
                    <a id ="Phoby" >
                    <div class="param-name">Фобія</div>
                    <div class="param-value">Мегалофобія</div>
                    </a>
                    <a id ="Hoby" >
                    <div class="param-name">Хобі</div>
                    <div class="param-value">Музика</div>
                    </a>
                    <a id ="Dop_info" >
                    <div class="param-name">Доп. інформація</div>
                    <div class="param-value">Має великий хуй</div>
                    </a>
                    <a id ="knowlage" >
                    <div class="param-name">Знання</div>
                    <div class="param-value">Знає в кого маленький хуй</div>
                    </a>
                </div>
                <div class="action-card use-card">
                    <div class="card-name">Картка дії</div>
                    <div class="card-description">Якась хуйня залупна, яку ніхто не буде читати, бо всі їбали рот автора і його намагання створити нормальну гру. Життя несправедливе, піду плакать.</div>
                </div>
                <div class="condition-card use-card">
                    <div class="card-name">Картка умови</div>
                    <div class="card-description">Якась хуйня залупна, яку ніхто не буде читати, бо всі їбали рот автора і його намагання створити нормальну гру. Життя несправедливе, піду плакать.</div>
                </div>
            </div>--%>
        </div>
    </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-3.4.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <script src="../wwwroot/js/script.js"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript"> $(function () {
       $(document).ready(function () {
           console.log(<% = Session["playersAmount"] %>);
           for(let i = 0; i < <% = Session["playersAmount"] %>; i++){
               $(".player-slider").append('<div class="player-card-wrapper">Some player</div>')
           }
               
            $(".player-slider").append('<div class="player-card-wrapper"><% = Session["Name"] %></div>');
            $(".player-slider").slick({
               slidesToShow: 1,
               prevArrow:"<button type='button' class='slick-prev pull-left'><i class='fa fa-angle-left' aria-hidden='true'></i></button>",
               nextArrow:"<button type='button' class='slick-next pull-right'><i class='fa fa-angle-right' aria-hidden='true'></i></button>"
           });
        })
        /* 
        // Declare a proxy to reference the hub.
        var game = $.connection.servHub;
        // Create a function that the hub can call to broadcast messages.
        chat.client.broadcastMessage = function (name, message) {

        };
        $('#displayname').val('*/<% = Session["Name"] %>/*');
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    game.server.send();

                });
            });*/
        });
    </script>

</asp:Content>

