<%@ Page Title="Game Page" Language="C#" MasterPageFile="~/Pages/Site.Master" AutoEventWireup="true" CodeBehind="Game.aspx.cs" Inherits="BUNKER.Pages.Game" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div class="content-wrapper">
      <div class="player-slider">
          <div class="player-card-wrapper" id = "<%=BUNKER.GlobalVar.GetPlayers()[Convert.ToInt32(Application["TotalOnlineUsers"])].name.ToString()%>">
                    <div class="player-card-inner">
                        <h3 class= "player-name" id = "player_name" > <% = BUNKER.GlobalVar.GetPlayers()[Convert.ToInt32(Application["TotalOnlineUsers"])].name.ToString() %></h3> 
                        <a id = "Job" >
                        <div class="param-name">Професія</div>
                        <div class="param-value"><% = BUNKER.GlobalVar.GetPlayers()[Convert.ToInt32(Application["TotalOnlineUsers"])].job.ToString() %></div>
                        </a>
                        <a id ="Bio" >
                        <div class="param-name">Біо характеристики</div>
                        <div class="param-value revealed"><% = BUNKER.GlobalVar.GetPlayers()[Convert.ToInt32(Application["TotalOnlineUsers"])].bio.ToString() %>, 29 р.</div>
                        </a>
                        <a id ="Heath" >
                        <div class="param-name">Хвороба</div>
                        <div class="param-value">Дислексія</div>
                        </a>
                        <a id ="Phoby" >
                        <div class="param-name">Фобія</div>
                        <div class="param-value">Мегалофобія</div>
                        </a>
                        <a id ="Hoby" >
                        <div class="param-name">Хобі</div>
                        <div class="param-value">Музика</div>
                        </a>
                        <a id ="Dop_info" >
                        <div class="param-name">Доп. інформація</div> 
                        <div class="param-value">Має великий хуй</div>
                        </a>
                        <a id ="knowlage" >
                        <div class="param-name">Знання</div>
                        <div class="param-value">Знає в кого маленький хуй</div>
                        </a>
                    </div>
                    <div class= "action-card use-card" >
                        <div class="card-name">Картка дії</div>
                        <div class="card-description">Якась хуйня</div>
                    </div>
                    <div class="condition-card use-card">
                        <div class="card-name">Картка умови</div>
                        <div class="card-description">Якась.</div>
                    </div >
               </div >
        </div>
    </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-3.4.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <script src="../wwwroot/js/script.js"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript"> $(function () {
     var game = $.connection.servHub;
         $(document).ready(function () {
             console.log(<% = Application["TotalOnlineUsers"] %>);
           <%if (Convert.ToInt32(Application["TotalOnlineUsers"]) >= 2) {
             for(int i = 1; i < Convert.ToInt32(Application["TotalOnlineUsers"]); i++) { %>
             $(".player-slider").append('<div class="player-card-wrapper" id = "<%=i%>">\
                    <div class="player-card-inner">\
                        <h3 class= "player-name" id = "player_name" > <% = BUNKER.GlobalVar.GetPlayers()[i].name.ToString() %></h3> \
                        <a id = "Job" >\
                        <div class="param-name">Професія</div>\
                        <div class="param-value">---</div>\
                        </a>\
                        <a id ="Bio" >\
                        <div class="param-name">Біо характеристики</div>\
                        <div class="param-value revealed">---</div>\
                        </a>\
                        <a id ="Heath" >\
                        <div class="param-name">Хвороба</div>\
                        <div class="param-value"></div>\
                        </a>\
                        <a id ="Phoby" >\
                        <div class="param-name">Фобія</div>\
                        <div class="param-value"></div>\
                        </a>\
                        <a id ="Hoby" >\
                        <div class="param-name">Хобі</div>\
                        <div class="param-value"></div>\
                        </a>\
                        <a id ="Dop_info" >\
                        <div class="param-name">Доп. інформація</div>\
                        <div class="param-value"></div>\
                        </a>\
                        <a id ="knowlage" >\
                        <div class="param-name">Знання</div>\
                        <div class="param-value"></div>\
                        </a>\
                    </div>\
                    <div class= "action-card use-card" >\
                        <div class="card-name">Картка дії</div>\
                        <div class="card-description"></div>\
                    </div>\
                    <div class="condition-card use-card">\
                        <div class="card-name">Картка умови</div>\
                        <div class="card-description"></div>\
                    </div >\
               </div > ')

           <% } %>
             <% } %>
             $(".player-slider").slick({
                 slidesToShow: 1,
                 prevArrow: "<button type='button' class='slick-prev pull-left'><i class='fa fa-angle-left' aria-hidden='true'></i></button>",
                 nextArrow: "<button type='button' class='slick-next pull-right'><i class='fa fa-angle-right' aria-hidden='true'></i></button>"
             })

         })
 });

    </script>

</asp:Content>

