<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TestGenerator.aspx.cs" Inherits="BUNKER.Pages.TestGenerator" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" Height="47px" Text="Інфа" Width="240px" />
           <asp:Button ID="Button1" runat="server" Height="47px" OnClick="Button1_Click" Text="Вхід " Width="240px" />
        </div>
    
    <div id="usersCount">test</div>
    <script src="../Scripts/jquery-3.4.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../wwwroot/js/signalr/dist/browser/signalr.js"></script>
    <script src="/signalr/hubs" type="text/javascript"></script>
     <script>
         $(function () {
             // Reference the auto-generated proxy for the hub.  
             var userActivity = $.connection.userConnectionHub;

             // Create a function that the hub can call back to display messages.

             userActivity.client.updateUsersOnlineCount = function (count) {
                 // Add the message to the page. 
                 $('#usersCount').text(count);
             };

             $.connection.hub.start();
         });
    </script>
        </form>
</body>
</html>
